name: Ktlint

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ktlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Composegram

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run ktlintCheck
      run: ./gradlew ktlintCheck
